export const metadata = {
  title: "rtklink | Terms and conditions",
  description: "Your positioning partner in the field",
};

const text: any = {
  title: {
    en: "General Terms and Conditions",
    es: "Terminos y condiciones",
  },
  law: {
    en: [
      "General: Unless otherwise expressly agreed in writing, all offers, orders, shipments, uses of rtklink’s firmware, software and hardware (“Products”), as well as all support and data services (“Data Services”) and third party software provided by rtklink (“Third Party Software”) are governed by these general terms and conditions (“General Terms and Conditions”). Any terms and conditions stipulated by the Customer which are different from the General Terms and Conditions shall apply only if expressly agreed by rtklink in writing. These General Terms and Conditions constitute the entire, complete and exclusive agreement between rtklink and the Customer (“the parties”). By taking delivery of Products or Third Party Software or by using support or Data Services, Customer accepts these General Terms and Conditions. Orders shall not be effective until they are confirmed by rtklink’s order confirmation.",
      "Conditions of use: rtklink Products and Data Services may not be used in weapons and weapon systems (e.g. systems for identifying targets or for the guidance of missiles, bombs or bullets), including for testing and simulation of such weapon systems. rtklink’s Products and Data Services are not intended for use as critical components in or in combination with (a) automated driving assistance device or system in any automotive application and mechanism, or (b) any kind of medical life-saving or life support device or system (including any device or system that is intended for surgical implant into the human body or to support or sustain life) and whose malfunction or failure to perform may result in significant injury or death to the user, or (c) any nuclear facilities, or (d) any air traffic control device, application or system, or (e) any other device, application or system where it is reasonably foreseeable that failure of the Product(s) as used in such device, application or system would lead to death, bodily injury or property damage. A component is critical when its malfunction or failure to perform may cause the failure of a device or system, or may affect the effectiveness of such device or system. Any use for which rtklink Products and Data Services are not intended for is at customer’s risk and customer shall indemnify rtklink from claims resulting from such use.",
      "Cancellation: Only unshipped or unactivated Services can be cancelled. Cancellation fee is 10% of the total value of your order.",
      "Shipment: Products are shipped by rtklink at Customer’s cost to the address indicated in the order. All our goods are sent with unpaid duties (DDU Incoterm 2000) unless specified differently in the order confirmation. In case of loss or damage during transport, rtklink will take responsibility and will send a replacement.",
      "Payment Terms: online prices are only valid for prepayment. Other payment terms can be requested at a fee. All bank charges for wire transfer must be borne by the Customer. If Customer delays payment, default interest will be charged monthly towards consumers at 6 (six) percentage points above the then valid base interest rate published by the European Central Bank. rtklink’s right to claim a higher damage caused by the default is not limited thereby.",
      "Incoming Inspection: Customer shall perform incoming inspection as necessary to ascertain that the Products shipped correspond to the order confirmation. Customer may reject those Products that do not correspond to the order confirmation within five (5) business days from the receipt of shipment. In the event Customer does not reject the Products within the five (5) business day period, Customer shall be deemed to have accepted the delivered Products in full.",
      "Return Policy and Order Issues: check out our Returns and Order Issues page.",
      "Warranties: rtklink’s Product warranty applies for a period of 2 years from the date of delivery for any proven defects due to bad material or poor workmanship of rtklink. Under the warranty, rtklink undertakes, at its sole discretion, to repair or replace the defective hardware or to reimburse the purchase price for the defective hardware. It is the Customer’s responsibility to arrange and pay the return shipment of the defective hardware to rtklink. Return shipment will only be accepted if such shipment is approved by e-mail. Repaired or replaced hardware will be warranted hereunder only for the remaining portion of the original warranty period. Any guarantee or additional warranty, implied warranty (merchantability or fitness for a particular purpose) or any return due to reasons other than the above‑mentioned is expressly excluded. Any removed hardware shall become rtklink’s property. The Customer shall bear the associated costs of replacement of any defective hardware (i.e. removing, transporting and reinstalling). Excluded from rtklink’s warranty are all defects, which result from normal wear and tear or damaging external influences (e.g. electromagnetic, electrolytic, chemical, weather, air pollution), unapproved repairs, improper maintenance or storage, failure to observe the user manual and mounting instructions, excessive loading, inappropriate or insufficient testing, inappropriate material or processes, failure to implement updates or upgrades of firmware or software as recommended by rtklink. Before mass‑production, Customer shall perform tests as necessary to assure that the Products and Data Services are fit for the purpose intended by the Customer. A warranty claim must be made within three (3) days after discovery of the defect by Customer, otherwise rtklink’s warranty coverage shall not apply. Data Services and support are provided on an “as is” basis and rtklink, its affiliates and third party licensors expressly disclaim all warranties, whether express, implied or statutory.",
      "Data Services: rtklink grants Customer a non‑exclusive non‑transferable, license to use rtklink Data Services. Customer shall ensure that any system (e.g. Customer’s servers) containing the data or access credentials are kept secure and inaccessible to unauthorized third parties. In any event of a breach of Customer’s system, Customer shall notify rtklink immediately. Customer and its own customers are not permitted: (i) to make modifications or derivative works of the data or of the Data Services, (ii) to interfere with their performance, (iii) to use them in any illegitimate or illegal manner, or (iv) to reverse engineer, decompile, disassemble or otherwise attempt to discover their source code. rtklink reserves the right to refuse or interrupt the services for any reason such as maintenance, patches or upgrades and to disable or to completely deactivate any Customer access to the data without prior notification. rtklink Data Services are only to be used in combination with rtklink Products. The use of rtklink Data Services outside the specified use cases will lead to immediate interruption of the service and termination of the contract without compensation.",
      "Liability: rtklink excludes any liability for support and Data Services. rtklink’s maximum cumulative liability under the General Terms and Conditions and under any order, order confirmation or delivery is limited to the lesser of EUR 1’000 or the total payment received by rtklink from Customer for the Products and Data Services giving rise to the liability or indemnity obligation. Any liability which is not expressly mentioned under the General Terms and Conditions and any liability, without limitation, for indirect or consequential damages, loss of profit, irrespective of the grounds on which it is based (including late, partial or no delivery, infringement of intellectual property rights, tort, contract or strict liability), is excluded by rtklink to the maximum extent authorized by law. Customer using or selling Products in devices or systems where malfunction can result in personal injury or casualties, do so at their own risk and agree to hold rtklink harmless from any claims, liabilities or damages as a consequence. The use or sale of Products in countries subject to different regulations and standards than those in force at rtklink’s place of production, are at Customer’s risk. rtklink reserves the right to control the defense and settlement of any claim, for which rtklink has an obligation to indemnify hereunder. rtklink shall not be liable for non, partial or bad performance due to any event beyond its reasonable control, including, but not limited to, acts of God, floods, wars, fires, material shortages of suppliers, changes in government rules and regulations.",
      "Indemnification: Customer shall indemnify and hold rtklink harmless against any and all damages, liabilities, penalties, fines, costs, and expenses, including attorneys’ fees, arising out of claims, suit, allegations or charges of Customer’s failure to comply with the General Terms and Conditions.",
      "Technical Information: Instructions, recommendations, data and drawings in summaries, brochures, datasheets, manuals, catalogues and on rtklink’s website are not binding and do not constitute a warranty (express, implied or statutory). rtklink may modify such information at any time without notice.",
      "Export Control and Regulatory Requirements: Customer represents that the Product will not be shipped to any countries subject to embargo, export controls or other restrictions under any applicable law or regulation and that he/she is not on a denied person or entity list. At rtklink’s request, Customer will sign a letter confirming the above.",
      "Invoicing: invoices will be issued when the shipment departs rtklink facilities. The invoice date will be the last day of the month when the invoice is issued. In case of special requirements, please contact rtklink in advance.",
    ],
    es: [
      "Generalidades: A menos que se acuerde expresamente por escrito lo contrario, todas las ofertas, pedidos, envíos, usos del firmware, software y hardware de rtklink (en adelante, 'Productos'), así como todos los servicios de soporte y datos ('Servicios de Datos') y el software de terceros proporcionado por rtklink ('Software de Terceros') se rigen por estos términos y condiciones generales ('Términos y Condiciones Generales'). Cualquier término y condición estipulados por el Cliente que difieran de los Términos y Condiciones Generales se aplicarán únicamente si rtklink los acepta expresamente por escrito. Estos Términos y Condiciones Generales constituyen el acuerdo completo, total y exclusivo entre rtklink y el Cliente ('las partes'). Al recibir los Productos o el Software de Terceros o al utilizar los Servicios de Soporte o los Servicios de Datos, el Cliente acepta estos Términos y Condiciones Generales. Los pedidos no serán efectivos hasta que sean confirmados por la confirmación del pedido de rtklink.",
      "Condiciones de uso: Los Productos y Servicios de Datos de rtklink no pueden utilizarse en armas y sistemas de armas (por ejemplo, sistemas para identificar objetivos o para la guía de misiles, bombas o balas), incluido el uso para pruebas y simulaciones de dichos sistemas de armas. Los Productos y Servicios de Datos de rtklink no están destinados a ser utilizados como componentes críticos en combinación con (a) dispositivos o sistemas de asistencia para la conducción automatizada en cualquier aplicación y mecanismo automotriz, ni (b) ningún tipo de dispositivo o sistema de soporte vital o salvamento médico (incluido cualquier dispositivo o sistema que esté destinado a ser implantado quirúrgicamente en el cuerpo humano o para soportar o mantener la vida) y cuyo mal funcionamiento o falta de rendimiento pueda resultar en lesiones o muerte del usuario, ni (c) instalaciones nucleares, ni (d) dispositivos, aplicaciones o sistemas de control de tráfico aéreo, ni (e) cualquier otro dispositivo, aplicación o sistema donde sea razonablemente previsible que la falla de los Productos utilizados en dicho dispositivo, aplicación o sistema pueda conducir a la muerte, lesiones corporales o daños materiales. Un componente se considera crítico cuando su mal funcionamiento o falta de rendimiento puede causar la falla de un dispositivo o sistema, o puede afectar la eficacia de dicho dispositivo o sistema. Cualquier uso para el cual los Productos y Servicios de Datos de rtklink no estén destinados es responsabilidad del cliente y el cliente deberá indemnizar a rtklink por reclamaciones resultantes de dicho uso.",
      "Cancelación: Solo se pueden cancelar los Servicios no enviados o no activados. La tarifa de cancelación es del 10% del valor total de su pedido.",
      "Envío: Los Productos son enviados por rtklink a cargo del Cliente a la dirección indicada en el pedido. Todos nuestros productos se envían sin derechos pagados (Incoterm 2000 DDU) a menos que se especifique lo contrario en la confirmación del pedido. En caso de pérdida o daño durante el transporte, rtklink asumirá la responsabilidad y enviará un reemplazo.",
      "Términos de pago: los precios en línea solo son válidos para el pago por adelantado. Se pueden solicitar otros términos de pago con un cargo adicional. Todos los cargos bancarios por transferencia bancaria deben ser sufragados por el Cliente. Si el Cliente retrasa el pago, se le cobrará un interés de demora mensual del 6% sobre la tasa de interés base vigente publicada por el Banco Central Europeo. El derecho de rtklink a reclamar un daño mayor causado por el incumplimiento no está limitado por ello.",
      "Inspección de entrada: El Cliente deberá realizar la inspección de entrada necesaria para asegurarse de que los Productos enviados corresponden a la confirmación del pedido. El Cliente puede rechazar aquellos Productos que no correspondan a la confirmación del pedido dentro de los cinco (5) días hábiles a partir de la recepción del envío. En caso de que el Cliente no rechace los Productos dentro del período de cinco (5) días hábiles, se considerará que el Cliente ha aceptado los Productos entregados en su totalidad.",
      "Política de Devoluciones y Problemas con el Pedido: consulta nuestra página de Devoluciones y Problemas con el Pedido.",

      'Garantías: La garantía de los Productos de rtklink se aplica por un período de 2 años a partir de la fecha de entrega por cualquier defecto probado debido a materiales defectuosos o mano de obra deficiente de rtklink. En virtud de la garantía, rtklink se compromete, a su entera discreción, a reparar o reemplazar el hardware defectuoso o reembolsar el precio de compra del hardware defectuoso. Es responsabilidad del Cliente organizar y pagar el envío de devolución del hardware defectuoso a rtklink. El envío de devolución solo se aceptará si dicho envío es aprobado por correo electrónico. El hardware reparado o reemplazado estará garantizado únicamente por el período restante del período de garantía original. Queda expresamente excluida cualquier garantía o garantía adicional, garantía implícita (comerciabilidad o idoneidad para un fin particular) o cualquier devolución debido a motivos diferentes a los mencionados anteriormente. Cualquier hardware retirado se convertirá en propiedad de rtklink. El Cliente deberá asumir los costos asociados al reemplazo de cualquier hardware defectuoso (es decir, extracción, transporte y reinstalación). Se excluyen de la garantía de rtklink todos los defectos que resulten del desgaste normal o influencias externas perjudiciales (como electromagnéticas, electrolíticas, químicas, climáticas, contaminación del aire), reparaciones no autorizadas, mantenimiento o almacenamiento incorrectos, incumplimiento del manual de usuario e instrucciones de montaje, carga excesiva, pruebas inadecuadas o insuficientes, material o procesos inapropiados, falta de implementación de actualizaciones o mejoras de firmware o software recomendadas por rtklink. Antes de la producción en masa, el Cliente deberá realizar pruebas según sea necesario para asegurar que los Productos y Servicios de Datos sean adecuados para el propósito previsto por el Cliente. Una reclamación de garantía debe realizarse dentro de los tres (3) días posteriores al descubrimiento del defecto por parte del Cliente, de lo contrario, la cobertura de garantía de rtklink no se aplicará. Los Servicios de Datos y el soporte se proporcionan en base a  "tal cual" y rtklink, sus afiliados y licenciantes de terceros renuncian expresamente a todas las garantías, ya sean expresas, implícitas o estatutarias.',

      "Servicios de Datos: rtklink concede al Cliente una licencia no exclusiva y no transferible para utilizar los Servicios de Datos de rtklink. El Cliente deberá asegurarse de que cualquier sistema (por ejemplo, servidores del Cliente) que contenga los datos o las credenciales de acceso se mantenga seguro e inaccesible para terceros no autorizados. En caso de violación del sistema del Cliente, el Cliente deberá notificar a rtklink de inmediato. Al Cliente y a sus propios clientes no se les permite: (i) realizar modificaciones o trabajos derivados de los datos o los Servicios de Datos, (ii) interferir en su rendimiento, (iii) utilizarlos de manera ilegítima o ilegal, o (iv) realizar ingeniería inversa, descompilar, desensamblar o intentar descubrir su código fuente. rtklink se reserva el derecho de rechazar o interrumpir los servicios por cualquier motivo, como mantenimiento, parches o actualizaciones, y desactivar o desactivar por completo cualquier acceso del Cliente a los datos sin previo aviso. Los Servicios de Datos de rtklink solo deben usarse en combinación con los Productos de rtklink. El uso de los Servicios de Datos de rtklink fuera de los casos de uso especificados resultará en la interrupción inmediata del servicio y la terminación del contrato sin compensación.",
      "Responsabilidad: rtklink excluye cualquier responsabilidad por los servicios de soporte y los Servicios de Datos. La responsabilidad acumulada máxima de rtklink en virtud de los Términos y Condiciones Generales y cualquier pedido, confirmación de pedido o entrega se limita al menor de 1.000 EUR o el pago total recibido por rtklink del Cliente por los Productos y los Servicios de Datos que generen la responsabilidad u obligación de indemnización. Se excluye cualquier responsabilidad que no se mencione expresamente en los Términos y Condiciones Generales y cualquier responsabilidad, sin limitación, por daños indirectos o consecuentes, pérdida de beneficios, independientemente de los motivos en los que se base (incluida la entrega tardía, parcial o nula, infracción de derechos de propiedad intelectual, responsabilidad extracontractual, contractual o estricta), por rtklink en la medida máxima permitida por la ley. El Cliente que utilice o venda Productos en dispositivos o sistemas en los que un mal funcionamiento pueda causar lesiones personales o daños, lo hace bajo su propio riesgo y acepta mantener indemne a rtklink de cualquier reclamo, responsabilidad o daño como consecuencia. El uso o venta de Productos en países sujetos a regulaciones y normas diferentes a las vigentes en el lugar de producción de rtklink es responsabilidad del Cliente. rtklink se reserva el derecho de controlar la defensa y el arreglo de cualquier reclamación por la cual rtklink tenga la obligación de indemnizar en virtud de los presentes. rtklink no será responsable de un rendimiento no, parcial o deficiente debido a cualquier evento fuera de su control razonable, incluidos, entre otros, actos de Dios, inundaciones, guerras, incendios, escasez de material de proveedores, cambios en las reglas y regulaciones gubernamentales.",
      "Indemnización: El Cliente indemnizará y mantendrá a rtklink indemne de cualquier daño, responsabilidad, penalidad, multa, costo y gasto, incluidos los honorarios de abogados, derivados de reclamaciones, demandas, alegaciones o cargos por el incumplimiento por parte del Cliente de los Términos y Condiciones Generales.",
      "Información Técnica: Las instrucciones, recomendaciones, datos y dibujos en resúmenes, folletos, hojas de datos, manuales, catálogos y en el sitio web de rtklink no son vinculantes y no constituyen una garantía (expresa, implícita o legal). rtklink puede modificar dicha información en cualquier momento sin previo aviso.",
      "Control de Exportación y Requisitos Regulatorios: El Cliente declara que el Producto no se enviará a países sujetos a embargos, controles de exportación u otras restricciones según cualquier ley o regulación aplicable y que no figura en una lista de personas o entidades denegadas. A solicitud de rtklink, el Cliente firmará una carta confirmando lo anterior.",
      "Facturación: las facturas se emitirán cuando el envío salga de las instalaciones de rtklink. La fecha de la factura será el último día del mes en que se emita la factura. En caso de requisitos especiales, comuníquese con rtklink con anticipación.",
    ],
  },
};

export default function Terms({ params }: { params: { lang: string } }) {
  return (
    <section className="px-20">
      <h3 className="text-center py-4 font-bold">{text.title[params.lang]}</h3>
      {text.law[params.lang].map((t: string, i: number) => {
        const label = t.split(":")[0];
        const text = t.split(":")[1];
        return (
          <p className="py-2 text-justify" key={i}>
            <strong>{label}: </strong>
            <span>{text}</span>
          </p>
        );
      })}
    </section>
  );
}
