export default function Terms() {
  const text: any = {
    law: {
      en: [
        "General: Unless otherwise expressly agreed in writing, all offers, orders, shipments, uses of rtklink’s firmware, software and hardware (“Products”), as well as all support and data services (“Data Services”) and third party software provided by rtklink (“Third Party Software”) are governed by these general terms and conditions (“General Terms and Conditions”). Any terms and conditions stipulated by the Customer which are different from the General Terms and Conditions shall apply only if expressly agreed by rtklink in writing. These General Terms and Conditions constitute the entire, complete and exclusive agreement between rtklink and the Customer (“the parties”). By taking delivery of Products or Third Party Software or by using support or Data Services, Customer accepts these General Terms and Conditions. Orders shall not be effective until they are confirmed by rtklink’s order confirmation.",
        "Conditions of use: rtklink Products and Data Services may not be used in weapons and weapon systems (e.g. systems for identifying targets or for the guidance of missiles, bombs or bullets), including for testing and simulation of such weapon systems. rtklink’s Products and Data Services are not intended for use as critical components in or in combination with (a) automated driving assistance device or system in any automotive application and mechanism, or (b) any kind of medical life-saving or life support device or system (including any device or system that is intended for surgical implant into the human body or to support or sustain life) and whose malfunction or failure to perform may result in significant injury or death to the user, or (c) any nuclear facilities, or (d) any air traffic control device, application or system, or (e) any other device, application or system where it is reasonably foreseeable that failure of the Product(s) as used in such device, application or system would lead to death, bodily injury or property damage. A component is critical when its malfunction or failure to perform may cause the failure of a device or system, or may affect the effectiveness of such device or system. Any use for which rtklink Products and Data Services are not intended for is at customer’s risk and customer shall indemnify rtklink from claims resulting from such use.",
        "Cancellation: Only unshipped or unactivated Services can be cancelled. Cancellation fee is 10% of the total value of your order.",
        "Shipment: Products are shipped by rtklink at Customer’s cost to the address indicated in the order. All our goods are sent with unpaid duties (DDU Incoterm 2000) unless specified differently in the order confirmation. In case of loss or damage during transport, rtklink will take responsibility and will send a replacement.",
        "Payment Terms: online prices are only valid for prepayment. Other payment terms can be requested at a fee. All bank charges for wire transfer must be borne by the Customer. If Customer delays payment, default interest will be charged monthly towards consumers at 6 (six) percentage points above the then valid base interest rate published by the European Central Bank. rtklink’s right to claim a higher damage caused by the default is not limited thereby.",
        "Incoming Inspection: Customer shall perform incoming inspection as necessary to ascertain that the Products shipped correspond to the order confirmation. Customer may reject those Products that do not correspond to the order confirmation within five (5) business days from the receipt of shipment. In the event Customer does not reject the Products within the five (5) business day period, Customer shall be deemed to have accepted the delivered Products in full.",
        "Return Policy and Order Issues: check out our Returns and Order Issues page.",
        "Warranties: rtklink’s Product warranty applies for a period of 2 years from the date of delivery for any proven defects due to bad material or poor workmanship of rtklink. Under the warranty, rtklink undertakes, at its sole discretion, to repair or replace the defective hardware or to reimburse the purchase price for the defective hardware. It is the Customer’s responsibility to arrange and pay the return shipment of the defective hardware to rtklink. Return shipment will only be accepted if such shipment is approved by e-mail. Repaired or replaced hardware will be warranted hereunder only for the remaining portion of the original warranty period. Any guarantee or additional warranty, implied warranty (merchantability or fitness for a particular purpose) or any return due to reasons other than the above‑mentioned is expressly excluded. Any removed hardware shall become rtklink’s property. The Customer shall bear the associated costs of replacement of any defective hardware (i.e. removing, transporting and reinstalling). Excluded from rtklink’s warranty are all defects, which result from normal wear and tear or damaging external influences (e.g. electromagnetic, electrolytic, chemical, weather, air pollution), unapproved repairs, improper maintenance or storage, failure to observe the user manual and mounting instructions, excessive loading, inappropriate or insufficient testing, inappropriate material or processes, failure to implement updates or upgrades of firmware or software as recommended by rtklink. Before mass‑production, Customer shall perform tests as necessary to assure that the Products and Data Services are fit for the purpose intended by the Customer. A warranty claim must be made within three (3) days after discovery of the defect by Customer, otherwise rtklink’s warranty coverage shall not apply. Data Services and support are provided on an “as is” basis and rtklink, its affiliates and third party licensors expressly disclaim all warranties, whether express, implied or statutory.",
        "Data Services: rtklink grants Customer a non‑exclusive non‑transferable, license to use rtklink Data Services. Customer shall ensure that any system (e.g. Customer’s servers) containing the data or access credentials are kept secure and inaccessible to unauthorized third parties. In any event of a breach of Customer’s system, Customer shall notify rtklink immediately. Customer and its own customers are not permitted: (i) to make modifications or derivative works of the data or of the Data Services, (ii) to interfere with their performance, (iii) to use them in any illegitimate or illegal manner, or (iv) to reverse engineer, decompile, disassemble or otherwise attempt to discover their source code. rtklink reserves the right to refuse or interrupt the services for any reason such as maintenance, patches or upgrades and to disable or to completely deactivate any Customer access to the data without prior notification. rtklink Data Services are only to be used in combination with rtklink Products. The use of rtklink Data Services outside the specified use cases will lead to immediate interruption of the service and termination of the contract without compensation.",
        "Liability: rtklink excludes any liability for support and Data Services. rtklink’s maximum cumulative liability under the General Terms and Conditions and under any order, order confirmation or delivery is limited to the lesser of EUR 1’000 or the total payment received by rtklink from Customer for the Products and Data Services giving rise to the liability or indemnity obligation. Any liability which is not expressly mentioned under the General Terms and Conditions and any liability, without limitation, for indirect or consequential damages, loss of profit, irrespective of the grounds on which it is based (including late, partial or no delivery, infringement of intellectual property rights, tort, contract or strict liability), is excluded by rtklink to the maximum extent authorized by law. Customer using or selling Products in devices or systems where malfunction can result in personal injury or casualties, do so at their own risk and agree to hold rtklink harmless from any claims, liabilities or damages as a consequence. The use or sale of Products in countries subject to different regulations and standards than those in force at rtklink’s place of production, are at Customer’s risk. rtklink reserves the right to control the defense and settlement of any claim, for which rtklink has an obligation to indemnify hereunder. rtklink shall not be liable for non, partial or bad performance due to any event beyond its reasonable control, including, but not limited to, acts of God, floods, wars, fires, material shortages of suppliers, changes in government rules and regulations.",
        "Indemnification: Customer shall indemnify and hold rtklink harmless against any and all damages, liabilities, penalties, fines, costs, and expenses, including attorneys’ fees, arising out of claims, suit, allegations or charges of Customer’s failure to comply with the General Terms and Conditions.",
        "Technical Information: Instructions, recommendations, data and drawings in summaries, brochures, datasheets, manuals, catalogues and on rtklink’s website are not binding and do not constitute a warranty (express, implied or statutory). rtklink may modify such information at any time without notice.",
        "Export Control and Regulatory Requirements: Customer represents that the Product will not be shipped to any countries subject to embargo, export controls or other restrictions under any applicable law or regulation and that he/she is not on a denied person or entity list. At rtklink’s request, Customer will sign a letter confirming the above.",
        "Invoicing: invoices will be issued when the shipment departs rtklink facilities. The invoice date will be the last day of the month when the invoice is issued. In case of special requirements, please contact rtklink in advance.",
      ],
    },
  };
  return (
    <section className="px-20">
      <h1 className="text-3xl mt-10 font-semibold text-cyan-600 text-center mb-8">
        General terms and conditions
      </h1>
      {text.law.en.map((t: string, i: number) => {
        const label = t.split(":")[0];
        const text = t.split(":")[1];
        return (
          <p className="py-2 text-justify" key={i}>
            <strong>{label}: </strong>
            <span>{text}</span>
          </p>
        );
      })}
    </section>
  );
}
